name: Update JSON and m3u File

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Code ko checkout karen
        uses: actions/checkout@v3

      - name: Python ko set karen
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Zaruri packages ko install karen
        run: |
          python -m pip install --upgrade pip
          pip install playwright python-dotenv

      - name: Playwright browsers ko install karen
        run: python -m playwright install --with-deps

      - name: Python script ko run karen
        env:
          ICC_USERNAME: ${{ secrets.ICC_USERNAME }}
          ICC_PASSWORD: ${{ secrets.ICC_PASSWORD }}
        run: |
          curl -L --retry 3 --connect-timeout 10 -o iccnew.py ${{ secrets.ICC_PYTHON_SCRIPT }}
          python iccnew.py

      - name: Changes ko commit karen
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/abid58b/ICCPlaylist.git

      - name: Commit and push changes
        run: |
          git add icc.m3u
          git fetch origin main
          git reset --soft origin/main
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Fetch icc m3u latest data new"
            git push origin main
          fi
